### ISSUE TITLE
A few future course suggestions

### ISSUE THREAD

**Issue by krisselberg** [bootdotdev/curriculum#11]
Some specific courses that would be very helpful for me that I didn't see on the list are something like:

- Learn GraphQL
- Learn Mobile Backend Development
- Learn Security Best Practices (Go, Python, JavaScript)
- Learn Cloud Platforms (AWS, Google Cloud, Azure)
- Learn Natural Language Processing

Are there any plans for any of these courses? Thank you for all of the hard work you guys put into making such great courses!! (Also, not sure if this is the right place to put something like this, so please let me know if there is a different place to send feedback like this)

**Comment by wagslane** [comment]
Incorporated!
