### ISSUE TITLE
Python modulo usage before explanation

### ISSUE THREAD

**Issue by bpetermann** [bootdotdev/curriculum#14]
The modulo operator is first introduced in the solution to "Ch 7: Loops C4. Prime?". The explanation of the modulo operator, on the other hand, is not found until "Ch 8: Lists 16. Modulo operator in Python". Could be confusing.

**Comment by wagslane** [comment]
Please report content specific issues in the Boot.dev app itself, this repo is just for the curriculum! Thanks though
