### ISSUE TITLE
link to `Build a Pokedex on Command Line (Go)` is broken

### ISSUE THREAD

**Issue by Delta456** [bootdotdev/curriculum#15]
The link to the project [`Build a Pokedex on Command Line (Go)`](https://www.boot.dev/build/build-pokedex-cli) is broken and shows error 404.

![image](https://github.com/bootdotdev/curriculum/assets/28479139/72248dbb-0b14-4e8c-a56a-da3d2e37c9c8)

**Comment by wagslane** [comment]
Fixed thanks!
