### ISSUE TITLE
Incorrect answer in Functions Quiz Ch 3.9 in Learn Python

### ISSUE THREAD

**Issue by markalanboyd** [bootdotdev/curriculum#18]
I believe the answer here should be "slots" not "parameters."

![Screenshot 2023-12-08 at 12 12 43](https://github.com/bootdotdev/curriculum/assets/10804241/5f7573b6-b2ee-41f5-80f4-6918449e2a6f)

**Comment by marceloacosta** [comment]
just tested it and it works correctly
<img width="802" alt="image" src="https://github.com/bootdotdev/curriculum/assets/4666796/d3421e5b-1a52-404a-a56a-2d92f52e696e">
<img width="802" alt="image" src="https://github.com/bootdotdev/curriculum/assets/4666796/3bcca6b7-dc4a-4222-8fad-71d86b1d5436">

**Comment by wagslane** [comment]
@markalanboyd Thanks! This repo is just for the curriculum though! If you find problems with a lesson be sure to report it directly in the app, thanks!!!
