### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by scchi** [bootdotdev/curriculum#2]
**URL:**           https://boot.dev/course/2af5c197-21eb-48b4-bd90-b0d59adb311e/eca6fbac-01a2-4b03-9837-e2242d665e21/7e8e6413-34a8-41bd-afb2-4e342a40f23f

**Correction:** 'aaway' to 'away'

![typo](https://user-images.githubusercontent.com/10018361/162665641-6e5a2c15-000e-4e72-919b-b116d9dcc3d5.png)

@wagslane

**Comment by wagslane** [comment]
Thanks ! I'll get this fixed. You can also more easily report issues in the
app using the comment bubble in the top right corner.

**Comment by wagslane** [comment]
Oh NVM, I'm an idiot. I thought this was in a course haha, this is the
right way to report.

**Comment by scchi** [comment]
It's actually in the Basic Intro to Coding course. I'll use the comment bubble next time.
