### ISSUE TITLE
Minor Typo in the CS track

### ISSUE THREAD

**Issue by akashdeepghosh** [bootdotdev/curriculum#4]
**Issue:** There is a minor typo in the first line.

**Link to Issue**: https://boot.dev/tracks/computer-science

**Steps to Reproduce the Problem**: Open the [CS track homepage](https://boot.dev/tracks/computer-science)

**Expected**: This **is** the one-and-only learning path on Boot.dev

**Actual:** This the one-and-only learning path on Boot.dev

**Screenshot:**
![image](https://user-images.githubusercontent.com/43311467/183266538-22e69915-d435-4fca-a7af-1a4a7fe99c06.png)

**Comment by wagslane** [comment]
Thanks resolved!
