### ISSUE TITLE
Proposal for JS rework

### ISSUE THREAD

**Issue by wagslane** [bootdotdev/curriculum#5]
1. Learn Coding Basics in Python (Skip if not brand new to coding)
2. Learn Python (Skip if not new to python)
3. Learn OOP
4. Build Dev Env Setup
5. Learn Algos
6. Learn DS
7. Build Maze Solver
8. Learn Advanced Algos
9. Personal Project 1
10. Learn JS
11. Learn HTTP
12. SEO Analyzer in Node.js (convert to Node, we need HTTP for this)
13. Learn 2D Graphics
14. Learn Functional Programming
15. Learn Go
16. ... rest is the same

Here are some of my thoughts:

* Python is easier to start with than JS
* It just makes the most sense to use `fetch()` to teach HTTP so JS makes sense
* Group FP with the rest of JS
* Simplifies the "where to start problem" (there are really only 3 places to start, and they're all at the beginning)
* Allows us to teach more advanced & modern JS in "learn js" which is nice.
* Not starting with JS will solidify the look that this is backend focused

---

* Slight concern that lack of visuals at the beginning won't be as fun
* 2D graphics is still out-of-place

**Comment by ALires** [comment]
I thought I had stuff to add to this but I honestly like how it looks. Just reading over it - the flow feels waaaayy better. And I like the idea of using Node and express - just a good skill to have. 

Should add the thought about the *syllabus* course?

0. Learn Boot.dev (idk bout the name) - We had talked about maybe scrapping this idea, but wanted it here so we could at least talk about it.
